
# Uncomment the following line to enable the OLED Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

# Re-enable nRF52840 high-voltage DC-DC for battery life (disabled by default in main)
CONFIG_SOC_DCDC_NRF52X_HV=y
