manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Nicell
      url-base: https://github.com/Nicell
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.2.1
      import: app/west.yml
    - name: nice-view-gem
      remote: Nicell
      revision: main
  self:
    path: config
